config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  get 'about'  => 'top#about', as: 'about'
  resource :sessions, only: [:create, :destroy], as: 'login', path: 'login'
  delete 'logout' => 'sessions#destroy', as: 'logout'

  resources :users do
    resources :orders, only: [:index, :show, :destroy]
  end
  resources :products

  resource :orders do
    collection do
      post 'new/confirmation'  => 'orders#new_confirmation'
    end
  end

  resource :giftboxes, only: [:new, :create] do
    collection do
      post 'new/check' => 'giftboxes#check_product', as: 'check'
      delete 'delete/check' => 'giftboxes#uncheck_product', as: 'uncheck'

      post 'new/confirmation'  => 'giftboxes#new_confirmation'
    end
  end

  namespace :admin do
    root to: 'products#index'
    resources :products do
      member do
        patch 'edit/confirmation' => 'products#edit_confirmation'
      end
      collection do
        post 'new/confirmation'  => 'products#new_confirmation'
      end
    end
    resources :users do
      resources :orders
    end
    resources :orders, only: [:index]

    resources :rules, path: :setting, only: [:index, :new, :create, :destroy]
  end

  match '*anything' => 'top#not_found', via: [:get, :post, :patch, :delete]
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id          :integer          not null, primary key
#  product_id  :integer          not null
#  user_id     :integer          not null
#  wrapping_id :integer          not null
#  dest        :text             not null
#  zipcode     :string           not null
#  payment     :string           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Order < ActiveRecord::Base
  extend Enumerize

  # 関連
  belongs_to :user
  belongs_to :product
  belongs_to :wrapping

  accepts_nested_attributes_for :user
  accepts_nested_attributes_for :product
  accepts_nested_attributes_for :wrapping


  # 定義
  enumerize :payment, in: [:cash, :credit, :delivery]


  # 委譲メソッド
  def product_name; product.name end
  def product_price; product.price end
  def product_weight; product.weight end
  def product_stock; product.stock end
  def product_note; product.note end
  def wrapping_name; wrapping.try(:name) end
  def user_email; user.email end


  # バリデーション
  validates :product_id,  presence: true

  validates :user_id,     presence: true

  validates :wrapping_id, presence: true

  validates :dest,        presence: {
                            allow_blank: true,
                          }

  validates :zipcode,     presence: true,
                          format: {
                            allow_blank: true,
                            with: /\A\d{3}[-]\d{4}/,
                          }
  validates :payment,     presence: true
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  price      :integer          not null
#  weight     :integer          not null
#  stock      :integer          not null
#  note       :text             not null
#  image      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Product < ActiveRecord::Base
  mount_uploader :image, ImageUploader


  # 関連

  # 商品 カテゴリ
  has_many :product_categories, dependent: :destroy
  has_many :categories, through: :product_categories

  # 注文
  has_many :orders, dependent: :destroy

  # 商品 ギフトボックス
  has_many :box_details, dependent: :destroy
  has_many :giftboxes, through: :box_details


  # バリデーション
  validates :name,      presence: true

  validates :price,     presence: true,
                        numericality: {
                          allow_blank: true,
                          greater_than: 0,
                          only_integer: true,
                        }

  validates :weight,    presence: true,
                        numericality: {
                          allow_blank: true,
                          greater_than: 0,
                          only_integer: true,
                        }

  validates :stock,     presence: true,
                        numericality: {
                          allow_blank: true,
                          greater_than_or_equal_to: 0,
                          only_integer: true,
                        }

  validates :note,      presence: true,
                        length: {
                          maximum: 500,
                          allow_blank: true,
                        }

  validate :check_image


  # プライベートメソッド
  private

  def check_image
    if self.image
      if self.image.size > 10.megabytes
        errors.add(:image, :too_big_image)
      end
    end
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::Base

  def index
    if params[:user_id].present?
      @user = User.find(params[:user_id])
      @orders = @user.orders.includes(:product, :wrapping).order(created_at: :DESC).page(params[:page])
    else
      @orders = Order.includes(:user, :product, :wrapping).order(created_at: :DESC).page(params[:page])
    end
  end

  def show
    @user = User.find(params[:user_id])
    @order = @user.orders.find(params[:id])
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    flash[:notice] = '注文を削除しました。'
    if params[:user].present?
      redirect_to admin_user_orders_path(params[:user_id])
    else
      redirect_to admin_orders_path
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < MemberController
  before_action :user_authorization, only: [:index, :show, :destroy]

  def index
    @orders = Order.includes(:product, :wrapping)
      .where(user_id: params[:user_id]).order(created_at: :DESC).page(params[:page])
  end

  def show
    @user = User.find(params[:user_id])
    @order = @user.orders.find(params[:id])
  end

  def new
    @order = current_user.orders.build(product_id: params[:product_id])
    redirect_to products_path, alert: "申し訳ありません。在庫がございません。" if @order.product.stock <= 0
    @order.product.stock -= 1
    @wrapping = Wrapping.all.pluck(:name, :id)
  end

  def create
    @order = current_user.orders.build(order_params)
    return redirect_to products_path, alert: "申し訳ありません。在庫がございません。" if @order.product.stock <= 0
    @order.product.stock -= 1
    @wrapping = Wrapping.all.pluck(:name, :id)
    if params[:back].present?
      render 'new'
    elsif @order.save
      redirect_to user_order_path(@order.user_id, @order.id), notice: '注文を承りました。'
    else
      render 'new'
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.product.stock += 1
    @order.save
    @order.destroy
    flash[:notice] = '注文をキャンセルしました。'
    destroy_giftbox_product!
    redirect_to user_orders_path
  end

  def new_confirmation
    @order = current_user.orders.build(order_params)
    return redirect_to products_path, alert: "申し訳ありません。在庫がございません。" if @order.product.stock <= 0
    @wrapping = Wrapping.all.pluck(:name, :id)
    render 'new' if @order.invalid?
  end


  private

  def order_params
    attrs = [:product_id, :wrapping_id, :dest, :zipcode, :payment]
    attrs << [:confirm]
    attrs << { product_attributes: [:id] }
    params.require(:order).permit(attrs)
  end

  def destroy_giftbox_product!
    if @order.product.note == 'ギフトボックス'
      @order.product.destroy
    end
  end
end

app/views/admin/orders/_form.html.erb
<%= form_for [:admin, @user, @order], class: 'form-horizontal' do |f| %>
  <%= f.fields_for :product do |ff| %>

    <%= f.fields_for :user do |ff| %>
      <div class="form-group">
        <%= ff.label :id, class: 'control-label col-md-12' %>
        <div class="col-md-1">
          <%= ff.number_field :id, class: 'form-control', disabled: true %>
        </div>
      </div>
      <div class="form-group">
        <%= ff.label :email, class: 'control-label col-md-12' %>
        <div class="col-md-12">
          <%= ff.text_field :email, class: 'form-control', disabled: true %>
        </div>
      </div>
    <% end %>

    <div class="form-group">
      <%= ff.label :created_at, class: 'control-label col-md-12' %>
      <div class="col-md-12">
        <%= ff.text_field :created_at, class: 'form-control', disabled: true %>
      </div>
    </div>

    <div class="form-group">
      <%= ff.label '請求金額', class: 'control-label col-md-12' %>
      <div class="col-md-12">
        <%= ff.number_field :price, class: 'form-control', disabled: true %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :payment, class: 'control-label col-md-12' %>
      <div class="col-md-12">
        <%= f.select :payment, Order.payment.options, {}, class: 'form-control', disabled: true %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :zipcode, class: 'control-label col-md-12' %>
      <div class="col-md-2">
        <span>〒</span>
        <%= f.text_field :zipcode, class: 'form-control', disabled: true %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :dest, class: 'control-label col-md-12' %>
      <div class="col-md-12">
        <%= f.text_field :dest, class: 'form-control', disabled: true %>
      </div>
    </div>

    <%= f.fields_for :wrapping do |ff| %>
      <div class="form-group">
        <%= ff.label :name, class: 'control-label col-md-12' %>
        <div class="col-md-12">
          <%= ff.text_area :name, class: 'form-control', disabled: true %>
        </div>
      </div>
    <% end %>
    <div class="form-group">
      <%= ff.label :name, class: 'control-label col-md-12' %>
      <div class="col-md-12">
        <%= ff.text_field :name, class: 'form-control', disabled: true %>
      </div>
    </div>

    <div class="form-group">
      <%= ff.label :price, class: 'control-label col-md-12' %>
      <div class="col-md-12">
        <%= ff.number_field :price, class: 'form-control', disabled: true %>
      </div>
    </div>

    <div class="form-group">
      <%= ff.label :weight, class: 'control-label col-md-12' %>
      <div class="col-md-12">
        <%= ff.number_field :weight, class: 'form-control', disabled: true %>
      </div>
    </div>

    <div class="form-group">
      <%= ff.label :note, class: 'control-label col-md-2' %>
      <div class="col-md-12">
        <%= ff.text_area :note, class: 'form-control', disabled: true %>
      </div>
    </div>
  <% end %>
  <%= f.fields_for :product do |ff| %>
    <div class="form-group">
      <b class="col-md-12">カテゴリ</b>
      <div class="chebox-inline col-md-12">
        <%= ff.collection_check_boxes :category_ids, Category.all, :id, :name do |fff| %>
          <%= fff.label { fff.check_box(disabled: true) + fff.text } %>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/admin/orders/index.html.erb
<% title = params[:user_id].present? ? 'ユーザID' + params[:user_id] + 'の注文一覧' : '注文一覧' %>
<% @page_title = '管理画面：' + title %>

<div class="page-header">
  <h1><%= title %></h1>
</div>

<% if @orders.present? %>
<div class="table-responsive">
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th class="text-center">メールアドレス</th>
        <th class="text-center">商品名</th>
        <th class="text-center">ラッピング</th>
        <th class="text-center">届け先</th>
        <th class="text-center">注文日時</th>
        <th class="text-center"></th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
      <tr>
        <td class="col-md-2"><%= order.user_email %></td>
        <td class="col-md-4"><%= order.product_name %></td>
        <td class="col-md-2"><%= order.wrapping_name %></td>
        <td class="col-md-2"><%= order.dest %></td>
        <td class="col-md-2"><%= h_datetime(order) %></td>
        <td class="text-center">
          <%= link_to '詳細', admin_user_order_path(order.user_id, order.id), class: 'btn btn-info btn-xs',
            style: 'width: 4em' %>
          <%= link_to '削除', admin_user_order_path(order.user_id, order.id, user: params[:user_id]), method: :delete, class: 'btn btn-xs btn-danger',
            style: 'width: 4em;', data: { disable_with: '削除中'} %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= paginate @orders %>
<% else %>
<p>注文がありません。</p>
<% end %>

app/views/admin/orders/show.html.erb
<% title = params[:user_id].present? ? 'ユーザID' + params[:user_id] + 'の注文詳細' : '注文詳細' %>
<% @page_title = '管理画面：' + title %>

<div class="page-header">
  <h1><%= title %></h1>
</div>

<%= render 'form' %>