config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  get 'about'  => 'top#about', as: 'about'
  resource :sessions, only: [:create, :destroy], as: 'login', path: 'login'
  delete 'logout' => 'sessions#destroy', as: 'logout'

  resources :users do
    resources :orders, only: [:index, :show, :destroy]
  end
  resources :products

  resource :orders do
    collection do
      post 'new/confirmation'  => 'orders#new_confirmation'
    end
  end

  resource :giftboxes, only: [:new, :create] do
    collection do
      post 'new/check' => 'giftboxes#check_product', as: 'check'
      delete 'delete/check' => 'giftboxes#uncheck_product', as: 'uncheck'

      post 'new/confirmation'  => 'giftboxes#new_confirmation'
    end
  end

  namespace :admin do
    root to: 'products#index'
    resources :products do
      member do
        patch 'edit/confirmation' => 'products#edit_confirmation'
      end
      collection do
        post 'new/confirmation'  => 'products#new_confirmation'
      end
    end
    resources :users do
      resources :orders
    end
    resources :orders, only: [:index]

    resources :rules, path: :setting, only: [:index, :new, :create, :destroy]
  end

  match '*anything' => 'top#not_found', via: [:get, :post, :patch, :delete]
end

app/views/shared/_errors.html.erb
<% if obj.errors.present? %>
<div id="errors">
  <h3>エラーがあります。</h3>
  <ul>
  <% obj.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-<%= type == 'notice' ? 'success' : 'danger' %>">
    <%= msg %>
    <a class="close" data-dismiss="alert">×</a>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <small>ギフト家</small>
  <nav>
    <ul>
      <li><%= link_to 'このサイトについて', about_path %></li>
    </ul>
  </nav>
</footer>

app/views/shared/_header.html.erb
<%= link_to 'ページトップ', root_path, class: "navbar-brand" %>
<div class="navbar-collapse collapse navbar-responsive-collapse">
  <ul class="nav navbar-nav">
    <li><%= link_to '商品一覧', products_path %></li>
    <% if current_user %>
    <li><%= link_to 'ギフト注文', new_giftboxes_path %></li>
    <li><%= link_to '注文一覧', user_orders_path(current_user) %></li>
    <li><%= link_to current_user.email + 'さん', edit_user_path(current_user) %></li>
    <li><%= link_to '管理画面', :admin_root if current_user.try(:administrator?) %></li>
    <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
    <% end %>
  </ul>
</div>

app/views/shared/_login_form.html.erb
<div>
  <h1>ログイン</h1>
  <%= form_tag :login, method: :post do %>
    <%= text_field_tag 'email' %>
    <%= password_field_tag 'password' %>
    <%= submit_tag 'ログイン', class: 'btn btn-primary' %>
  <% end %>
  <%= link_to '新規登録', new_user_path %>
</div>

app/views/shared/_sidebar.html.erb
<%= render 'shared/login_form' unless current_user %>