config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  get 'about'  => 'top#about', as: 'about'
  resource :sessions, only: [:create, :destroy], as: 'login', path: 'login'
  delete 'logout' => 'sessions#destroy', as: 'logout'

  resources :users do
    resources :orders, only: [:index, :show, :destroy]
  end
  resources :products

  resource :orders do
    collection do
      post 'new/confirmation'  => 'orders#new_confirmation'
    end
  end

  resource :giftboxes, only: [:new, :create] do
    collection do
      post 'new/check' => 'giftboxes#check_product', as: 'check'
      delete 'delete/check' => 'giftboxes#uncheck_product', as: 'uncheck'

      post 'new/confirmation'  => 'giftboxes#new_confirmation'
    end
  end

  namespace :admin do
    root to: 'products#index'
    resources :products do
      member do
        patch 'edit/confirmation' => 'products#edit_confirmation'
      end
      collection do
        post 'new/confirmation'  => 'products#new_confirmation'
      end
    end
    resources :users do
      resources :orders
    end
    resources :orders, only: [:index]

    resources :rules, path: :setting, only: [:index, :new, :create, :destroy]
  end

  match '*anything' => 'top#not_found', via: [:get, :post, :patch, :delete]
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  price      :integer          not null
#  weight     :integer          not null
#  stock      :integer          not null
#  note       :text             not null
#  image      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Product < ActiveRecord::Base
  mount_uploader :image, ImageUploader


  # 関連

  # 商品 カテゴリ
  has_many :product_categories, dependent: :destroy
  has_many :categories, through: :product_categories

  # 注文
  has_many :orders, dependent: :destroy

  # 商品 ギフトボックス
  has_many :box_details, dependent: :destroy
  has_many :giftboxes, through: :box_details


  # バリデーション
  validates :name,      presence: true

  validates :price,     presence: true,
                        numericality: {
                          allow_blank: true,
                          greater_than: 0,
                          only_integer: true,
                        }

  validates :weight,    presence: true,
                        numericality: {
                          allow_blank: true,
                          greater_than: 0,
                          only_integer: true,
                        }

  validates :stock,     presence: true,
                        numericality: {
                          allow_blank: true,
                          greater_than_or_equal_to: 0,
                          only_integer: true,
                        }

  validates :note,      presence: true,
                        length: {
                          maximum: 500,
                          allow_blank: true,
                        }

  validate :check_image


  # プライベートメソッド
  private

  def check_image
    if self.image
      if self.image.size > 10.megabytes
        errors.add(:image, :too_big_image)
      end
    end
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::Base

  def index
    @products = Product.includes(:categories).page(params[:page])
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if params[:back].present?
      render 'new'
    elsif @product.save
      redirect_to [:admin, @product], notice: '商品を新規登録しました。'
    else
      render 'new'
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.assign_attributes(product_params)
    #binding.pry
    if params[:back].present?
      @product.image.move_to_cache
      render 'edit'
    elsif @product.save
      redirect_to [:admin, @product], notice: '商品を更新しました。'
    else
      render 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to admin_products_path, notice: '商品を削除しました。'
  end

  def new_confirmation
    @product = Product.new(product_params)
    render 'new' if @product.invalid?
  end

  def edit_confirmation
    @product = Product.find(params[:id])
    @product.assign_attributes(product_params)
    render 'edit' if @product.invalid?
  end


  private

  def product_params
    attrs = [:name, :price, :weight, :stock, :note, :image, :image_cache]
    attrs << [:confirm]
    attrs << { categories_attributes: [:id, :name] }
    attrs << { category_ids: [] }
    params.require(:product).permit(attrs)
  end
end

app/controllers/products_controller.rb
class ProductsController < GuestController

  def index
    one = Product.includes(:categories)
    one = one.where.not('categories.name' => 'ギフトボックス', stock: 0)
    if params[:keyword].present?
      keyword = params[:keyword]
      like_keyword = '%' + keyword.downcase + '%'
      one = one.where('lower(products.name) like ? OR lower(categories.name) like ?', like_keyword, like_keyword)
    end
    @products = one.page(params[:page]).per(16)
  end

  def show
    @product = Product.find(params[:id])
    redirect_to products_path, alert: '申し訳ありません。在庫がございません。' if @product.stock <= 0
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def set_like_link(product)
    unless checked?(product.id)
      link_to '詰め合わせに追加', check_giftboxes_path(product_id: product, page: params[:page]), method: :post,
      class: 'btn btn-default'
    else
      link_to '詰め合わせから削除', uncheck_giftboxes_path(product_id: product, page: params[:page]), method: :delete,
      class: 'btn btn-link'
    end
  end
end

app/views/admin/products/_common_form.html.erb
<div class="form-group">
  <%= f.label :name, class: 'control-label col-md-12' %>
  <div class="col-md-12">
    <%= f.text_field :name, class: 'form-control', disabled: show? %>
  </div>
</div>

<div class="form-group">
  <%= f.label :price, class: 'control-label col-md-12' %>
  <div class="col-md-2">
    <%= f.number_field :price, class: 'form-control', disabled: show? %>
  </div>
</div>

<div class="form-group">
  <%= f.label :weight, class: 'control-label col-md-12' %>
  <div class="col-md-2">
    <%= f.number_field :weight, class: 'form-control', disabled: show? %>
  </div>
</div>

<div class="form-group">
  <%= f.label :stock, class: 'control-label col-md-12' %>
  <div class="col-md-2">
    <%= f.number_field :stock, class: 'form-control', disabled: show? %>
  </div>
</div>
<div class="form-group">
  <%= f.label :note, class: 'control-label col-md-12' %>
  <div class="col-md-12">
    <%= f.text_area :note, class: 'form-control', disabled: show? %>
  </div>
</div>

<div class="form-group">
  <%= f.label :image, class: 'control-label col-md-12'  %>
  <div class="col-md-4">
    <%= image_tag(@product.image.url) %>
    <%= f.file_field :image, disabled: show? %>
  </div>
</div>

<div class="form-group">
  <label class="col-md-12">カテゴリ</label>
  <div class="chebox-inline col-md-12">
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |ff| %>
      <%= ff.label { ff.check_box(disabled: show?) + ff.text } %>
    <% end %>
  </div>
</div>

<div class="form-group">
  <div class="col-md-offset-10 col-md-2">
    <%= link_to '編集', edit_admin_product_path(@product.id),
      class: 'btn btn-default' if show? %>
    <%= f.submit '更新', class: 'btn btn-primary' if edit_or_update? || edit_confirmation? %>
    <%= f.submit '新規作成', class: 'btn btn-primary' if new_or_create? || new_confirmation? %>
  </div>
</div>

app/views/admin/products/_confirm_form.html.erb
<%= f.hidden_field :name %>
<%= f.hidden_field :price %>
<%= f.hidden_field :weight %>
<%= f.hidden_field :stock %>
<%= f.hidden_field :note %>
<% @product.category_ids.each do |id| %>
  <%= hidden_field_tag 'product[category_ids][]', id %>
<% end %>

<h2>登録確認ページ</h2>

<div>
  <%= f.label :name, class: 'col-md-2' %>
  <div class="col-md-12">
    <%= @product.name %>
  </div>
</div>
<div>
  <%= f.label :price, class: 'col-md-2' %>
  <div class="col-md-12">
    <%= @product.price %>
  </div>
</div>
<div>
  <%= f.label :weight, class: 'col-md-2' %>
  <div class="col-md-12">
    <%= @product.weight %>
  </div>
</div>
<div>
  <%= f.label :stock, class: 'col-md-2' %>
  <div class="col-md-12">
    <%= @product.stock %>
  </div>
</div>
<div>
  <%= f.label :note, class: 'col-md-2' %>
  <div class="col-md-12">
    <%= @product.note %>
  </div>
</div>
<div>
  <b class="col-md-2">カテゴリ</b>
  <div class="col-md-12">
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |ff| %>
      <%= ff.label { ff.check_box(disabled: true) + ff.text } %>
    <% end %>
  </div>
</div>
<%= f.submit '戻る', name: :back, class: 'col-md-offset-10 col-md-2 btn, btn-default' %>
<%= f.submit '登録する', class: 'col-md-offset-10 col-md-2 btn, btn-danger' %>

app/views/admin/products/_confirmation.html.erb
<% @page_title = '管理画面：登録確認' %>

<%= form_for [:admin, @product], class: 'form-horizontal' do |f| %>
<%= f.hidden_field :name %>
<%= f.hidden_field :price %>
<%= f.hidden_field :weight %>
<%= f.hidden_field :stock %>
<%= f.hidden_field :note %>
<%= f.hidden_field :image_cache %>
<% @product.category_ids.each do |id| %>
  <%= hidden_field_tag 'product[category_ids][]', id %>
<% end %>

<h2>登録確認ページ</h2>

<div>
  <%= f.label :name, class: 'col-md-12' %>
  <div class="col-md-12">
    <%= @product.name %>
  </div>
</div>
<div>
  <%= f.label :price, class: 'col-md-12' %>
  <div class="col-md-12">
    <%= @product.price %>
  </div>
</div>
<div>
  <%= f.label :weight, class: 'col-md-12' %>
  <div class="col-md-12">
    <%= @product.weight %>
  </div>
</div>
<div>
  <%= f.label :stock, class: 'col-md-12' %>
  <div class="col-md-12">
    <%= @product.stock %>
  </div>
</div>
<div>
  <%= f.label :note, class: 'col-md-12' %>
  <div class="col-md-12">
    <%= @product.note %>
  </div>
</div>
<div class="form-group">
  <%= f.label :image, class: 'control-label col-md-12'  %>
  <div class="col-md-3">
    <%= image_tag(@product.image.url) %>
    <% f.file_field :image %>
  </div>
</div>
<div>
  <label class="col-md-12">カテゴリ</label>
  <div class="col-md-12">
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |ff| %>
      <%= ff.label { ff.check_box(disabled: true) + ff.text } %>
    <% end %>
  </div>
</div>
<%= f.submit '戻る', name: :back, class: 'col-md-offset-10 col-md-2 btn, btn-default' %>
<%= f.submit '登録する', class: 'col-md-offset-10 col-md-2 btn, btn-danger' %>
<% end %>

app/views/admin/products/_edit_form.html.erb
<%= render 'shared/errors', obj: @product %>

<%= form_for [:admin, @product], url: {action: 'edit_confirmation'}, class: 'form-horizontal' do |f| %>
  <%= render 'common_form', f:f %>
<% end %>

app/views/admin/products/_new_form.html.erb
<%= render 'shared/errors', obj: @product %>

<%= form_for [:admin, @product], url: {action: 'new_confirmation'}, class: 'form-horizontal' do |f| %>
  <%= render 'common_form', f:f %>
<% end %>

app/views/admin/products/edit.html.erb
<% @page_title = '管理画面：商品編集' %>

<div class="page-header">
  <h1>商品編集</h1>
</div>

<%= render 'edit_form' %>

app/views/admin/products/edit_confirmation.html.erb
<%= render 'confirmation' %>

app/views/admin/products/index.html.erb
<% @page_title = '管理画面：商品一覧' %>

<div class="page-header">
  <h1>商品一覧</h1>
</div>

<%= link_to '新規作成', new_admin_product_path, class: 'btn btn-primary' %>
<% if @products.present? %>
<div class="table-responsive">
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th class="text-center">名前</th>
        <th class="text-center">在庫数</th>
        <th class="text-center">価格</th>
        <th class="text-center">重さ</th>
        <th class="text-center">商品説明</th>
        <th class="text-center">カテゴリ</th>
        <th class="text-center"></th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
      <tr>
        <td class="col-md-2"><%= product.name %></td>
        <td class="text-right col-md-1"><%= number_with_delimiter(product.stock) %></td>
        <td class="text-right col-md-1"><%= number_with_delimiter(product.price) %></td>
        <td class="text-right col-md-1"><%= product.weight %></td>
        <td class="col-md-3"><%= product.note %></td>
        <td class="col-md-2"><%= tag_label(product) %></td>
        <td class="text-center col-md-2">
          <%= link_to '詳細', admin_product_path(product.id), class: 'btn btn-info btn-xs',
            style: 'width: 4em' %>
          <%= link_to '削除', admin_product_path(product.id), method: :delete, class: 'btn btn-xs btn-danger',
            style: 'width: 4em;', data: { disable_with: '削除中'} %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= paginate @products %>
<% else %>
<p>商品がありません。</p>
<% end %>

app/views/admin/products/new.html.erb
<% @page_title = '管理画面：商品登録' %>

<div class="page-header">
  <h1>商品登録</h1>
</div>

<%= render 'new_form' %>

app/views/admin/products/new_confirmation.html.erb
<%= render 'confirmation' %>

app/views/admin/products/show.html.erb
<% @page_title = '管理画面：商品詳細' %>

<div class="page-header">
  <h1>商品詳細</h1>
</div>

<%= render 'shared/errors', obj: @product %>

<%= form_for [:admin, @product], class: 'form-horizontal' do |f| %>
  <%= render 'common_form', f:f %>
<% end %>