config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  get 'about'  => 'top#about', as: 'about'
  resource :sessions, only: [:create, :destroy], as: 'login', path: 'login'
  delete 'logout' => 'sessions#destroy', as: 'logout'

  resources :users do
    resources :orders, only: [:index, :show, :destroy]
  end
  resources :products

  resource :orders do
    collection do
      post 'new/confirmation'  => 'orders#new_confirmation'
    end
  end

  resource :giftboxes, only: [:new, :create] do
    collection do
      post 'new/check' => 'giftboxes#check_product', as: 'check'
      delete 'delete/check' => 'giftboxes#uncheck_product', as: 'uncheck'

      post 'new/confirmation'  => 'giftboxes#new_confirmation'
    end
  end

  namespace :admin do
    root to: 'products#index'
    resources :products do
      member do
        patch 'edit/confirmation' => 'products#edit_confirmation'
      end
      collection do
        post 'new/confirmation'  => 'products#new_confirmation'
      end
    end
    resources :users do
      resources :orders
    end
    resources :orders, only: [:index]

    resources :rules, path: :setting, only: [:index, :new, :create, :destroy]
  end

  match '*anything' => 'top#not_found', via: [:get, :post, :patch, :delete]
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  administrator   :boolean          default(FALSE), not null
#  password_digest :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  include EmailAddressChecker

  before_save { email.downcase! }


  # 関連
  has_many :orders


  # バリデーション
  validate  :check_email

  validates :email,       presence: true,
                          uniqueness: { case_sensitive: false }

  validates :password,    presence: { on: :create, },
                          length: {
                            allow_blank: true,
                            minimum: 6,
                          }


  # メソッド
  has_secure_password


  # プライベートメソッド
  private

  def check_email
    if email.present?
      errors.add(:email, :invalid) unless well_formed_as_email_address(email)
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::Base

  def index
    @users = User.order(administrator: :DESC, id: :asc).page(params[:page])
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
  end

  def update
    @user = User.find(params[:id])
    @user.assign_attributes(user_params)
    if @user.save
      redirect_to admin_users_path, notice: 'ユーザを更新しました。'
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path, notice: 'ユーザを削除しました。'
  end

  private

  def user_params
    attrs = [:email, :administrator, :password, :password_confirmation]
    params.require(:user).permit(attrs)
  end
end

app/controllers/users_controller.rb
class UsersController < MemberController
  before_action :login_required, only: [:edit, :update]
  before_action :user_authorization, only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to :root, notice: 'ユーザを新規作成しました。'
    else
      render 'new'
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = User.find(params[:id])
    @user.assign_attributes(user_params)
    if @user.save
      redirect_to (@user.administrator? ? :admin_root : edit_user_path(@user)), notice: 'ユーザ情報を更新しました。'
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<div class="form-group">
  <%= f.label :email, class: 'control-label col-md-2' %>
  <div class="col-md-12">
    <%= f.email_field :email, class: 'form-control' %>
  </div>
</div>

<div class="form-group">
  <%= f.label :password, class: 'control-label col-md-2' %>
  <div class="col-md-12">
    <%= f.password_field :password, class: 'form-control' %>
  </div>
</div>

<div class="form-group">
  <%= f.label :password_confirmation, class: 'control-label col-md-2' %>
  <div class="col-md-12">
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>
</div>

<div class="form-group">
  <div class="col-md-12">
    <%= f.label :administrator %>
    <%= f.check_box :administrator, disabled: (current_user.id == params[:id].to_i) %>
  </div>
</div>

app/views/admin/users/edit.html.erb
<% @page_title = '管理画面：ユーザ編集' %>

<div class="page-header">
  <h1>ユーザの編集</h1>
</div>

<%= render 'shared/errors', obj: @user %>

<%= form_for [:admin, @user], class: 'form-horizontal' do |f| %>
  <%= render 'form', f: f %>
  <div class="form-group">
    <div class="col-md-offset-10 col-md-2">
      <%= f.submit 'ユーザを更新する', class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/admin/users/index.html.erb
<% @page_title = '管理画面：ユーザ一覧' %>

<div class="page-header">
  <h1>ユーザ一覧</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th class="text-center">id</th>
        <th class="text-center">メールアドレス</th>
        <th class="text-center">管理者</th>
        <th class="text-center"></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
      <tr>
        <td class="text-center"><%= user.id %></td>
        <td><%= user.email %></td>
        <td class="text-center"><%= '✓' if user.administrator? %></td>
        <td>
          <%= link_to '編集', edit_admin_user_path(user.id), class: 'btn btn-default btn-xs',
            style: 'width: 5em' %>
          <%= link_to_if (current_user.id != user.id), '削除', admin_user_path(user.id), method: :delete, class: 'btn btn-xs btn-danger', style: 'width: 5em;', data: { disable_with: '削除中'} %>
          <%= link_to '注文一覧', admin_user_orders_path(user.id), class: 'btn btn-info btn-xs',
            style: 'width: 5em' %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= paginate @users %>